[package]
name = "gitatui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
git2 = { version = "0.18", features = ["vendored-libgit2","vendored-openssl"]}
anyhow = "1.0"

[[bin]]
name = "gtu"
path = "src/main.rs"
